//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.16 at 11:08:08 ���� CST
//


package com.ppm.integration.agilesdk.connector.agm.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataTable complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataTable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Columns" type="{http://www.hp.com/ppm/integration/}Columns"/>
 *         &lt;element name="Rows" type="{http://www.hp.com/ppm/integration/}Rows"/>
 *         &lt;element name="MetadataAttributes" type="{http://www.hp.com/ppm/integration/}MetadataAttributes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataTable", namespace = "http://www.hp.com/ppm/integration/", propOrder = {
    "columns",
    "rows",
    "metadataAttributes"
})
public class DataTable {

    @XmlElement(name = "Columns", required = true)
    protected Columns columns;
    @XmlElement(name = "Rows", required = true)
    protected Rows rows;
    @XmlElement(name = "MetadataAttributes", required = true)
    protected MetadataAttributes metadataAttributes;

    /**
     * Gets the value of the columns property.
     *
     * @return
     *     possible object is
     *     {@link Columns }
     *
     */
    public Columns getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     *
     * @param value
     *     allowed object is
     *     {@link Columns }
     *
     */
    public void setColumns(Columns value) {
        this.columns = value;
    }

    /**
     * Gets the value of the rows property.
     *
     * @return
     *     possible object is
     *     {@link Rows }
     *
     */
    public Rows getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     *
     * @param value
     *     allowed object is
     *     {@link Rows }
     *
     */
    public void setRows(Rows value) {
        this.rows = value;
    }

    /**
     * Gets the value of the metadataAttributes property.
     *
     * @return
     *     possible object is
     *     {@link MetadataAttributes }
     *
     */
    public MetadataAttributes getMetadataAttributes() {
        return metadataAttributes;
    }

    /**
     * Sets the value of the metadataAttributes property.
     *
     * @param value
     *     allowed object is
     *     {@link MetadataAttributes }
     *
     */
    public void setMetadataAttributes(MetadataAttributes value) {
        this.metadataAttributes = value;
    }

}
