//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.06.12 at 10:29:05 PM CST
//


package com.ppm.integration.agilesdk.connector.agm.model.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityComplexType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EntityComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Fields" type="{http://www.hp.com/ppm/integration/sass/agm/model}FieldsComplexType"/>
 *         &lt;element name="RelatedEntities" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Relation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Entity" type="{http://www.hp.com/ppm/integration/sass/agm/model}EntityComplexType"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityComplexType", propOrder = {
    "fields",
    "relatedEntities"
})
public class EntityComplexType {

    @XmlElement(name = "Fields", required = true)
    protected FieldsComplexType fields;
    @XmlElement(name = "RelatedEntities")
    protected EntityComplexType.RelatedEntities relatedEntities;
    @XmlAttribute(name = "Type", required = true)
    protected String type;

    /**
     * Gets the value of the fields property.
     *
     * @return
     *     possible object is
     *     {@link FieldsComplexType }
     *
     */
    public FieldsComplexType getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     *
     * @param value
     *     allowed object is
     *     {@link FieldsComplexType }
     *
     */
    public void setFields(FieldsComplexType value) {
        this.fields = value;
    }

    /**
     * Gets the value of the relatedEntities property.
     *
     * @return
     *     possible object is
     *     {@link EntityComplexType.RelatedEntities }
     *
     */
    public EntityComplexType.RelatedEntities getRelatedEntities() {
        return relatedEntities;
    }

    /**
     * Sets the value of the relatedEntities property.
     *
     * @param value
     *     allowed object is
     *     {@link EntityComplexType.RelatedEntities }
     *
     */
    public void setRelatedEntities(EntityComplexType.RelatedEntities value) {
        this.relatedEntities = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Relation" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Entity" type="{http://www.hp.com/ppm/integration/sass/agm/model}EntityComplexType"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relation"
    })
    public static class RelatedEntities {

        @XmlElement(name = "Relation")
        protected List<EntityComplexType.RelatedEntities.Relation> relation;

        /**
         * Gets the value of the relation property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relation property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelation().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntityComplexType.RelatedEntities.Relation }
         *
         *
         */
        public List<EntityComplexType.RelatedEntities.Relation> getRelation() {
            if (relation == null) {
                relation = new ArrayList<EntityComplexType.RelatedEntities.Relation>();
            }
            return this.relation;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Entity" type="{http://www.hp.com/ppm/integration/sass/agm/model}EntityComplexType"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entity"
        })
        public static class Relation {

            @XmlElement(name = "Entity", required = true)
            protected EntityComplexType entity;
            @XmlAttribute(name = "Alias", required = true)
            protected String alias;

            /**
             * Gets the value of the entity property.
             *
             * @return
             *     possible object is
             *     {@link EntityComplexType }
             *
             */
            public EntityComplexType getEntity() {
                return entity;
            }

            /**
             * Sets the value of the entity property.
             *
             * @param value
             *     allowed object is
             *     {@link EntityComplexType }
             *
             */
            public void setEntity(EntityComplexType value) {
                this.entity = value;
            }

            /**
             * Gets the value of the alias property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getAlias() {
                return alias;
            }

            /**
             * Sets the value of the alias property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setAlias(String value) {
                this.alias = value;
            }

        }

    }

}
