//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.16 at 11:08:08 ���� CST
//


package com.ppm.integration.agilesdk.connector.agm.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GraphResult complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GraphResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataTable" type="{http://www.hp.com/ppm/integration/}DataTable"/>
 *         &lt;element name="Errors" type="{http://www.hp.com/ppm/integration/}Errors"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name = "GraphResult")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GraphResult", namespace = "http://www.hp.com/ppm/integration/", propOrder = {
    "date",
    "dataTable",
    "errors"
})
public class GraphResult {

    @XmlElement(name = "Date", required = true)
    protected String date;
    @XmlElement(name = "DataTable", required = true)
    protected DataTable dataTable;
    @XmlElement(name = "Errors", required = true)
    protected Errors errors;

    /**
     * Gets the value of the date property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the dataTable property.
     *
     * @return
     *     possible object is
     *     {@link DataTable }
     *
     */
    public DataTable getDataTable() {
        return dataTable;
    }

    /**
     * Sets the value of the dataTable property.
     *
     * @param value
     *     allowed object is
     *     {@link DataTable }
     *
     */
    public void setDataTable(DataTable value) {
        this.dataTable = value;
    }

    /**
     * Gets the value of the errors property.
     *
     * @return
     *     possible object is
     *     {@link Errors }
     *
     */
    public Errors getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     *
     * @param value
     *     allowed object is
     *     {@link Errors }
     *
     */
    public void setErrors(Errors value) {
        this.errors = value;
    }

}
