//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.06.12 at 10:29:05 PM CST
//


package com.ppm.integration.agilesdk.connector.agm.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.ppm.integration.agilesdk.connector.agm.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Entity_QNAME = new QName("http://www.hp.com/ppm/integration/sass/agm/model", "Entity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ppm.integration.agilesdk.connector.agm.model
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FieldComplexType }
     *
     */
    public FieldComplexType createFieldComplexType() {
        return new FieldComplexType();
    }

    /**
     * Create an instance of {@link EntityComplexType }
     *
     */
    public EntityComplexType createEntityComplexType() {
        return new EntityComplexType();
    }

    /**
     * Create an instance of {@link EntityComplexType.RelatedEntities }
     *
     */
    public EntityComplexType.RelatedEntities createEntityComplexTypeRelatedEntities() {
        return new EntityComplexType.RelatedEntities();
    }

    /**
     * Create an instance of {@link Entities }
     *
     */
    public Entities createEntities() {
        return new Entities();
    }

    /**
     * Create an instance of {@link FieldsComplexType }
     *
     */
    public FieldsComplexType createFieldsComplexType() {
        return new FieldsComplexType();
    }

    /**
     * Create an instance of {@link FieldComplexType.Value }
     *
     */
    public FieldComplexType.Value createFieldComplexTypeValue() {
        return new FieldComplexType.Value();
    }

    /**
     * Create an instance of {@link EntityComplexType.RelatedEntities.Relation }
     *
     */
    public EntityComplexType.RelatedEntities.Relation createEntityComplexTypeRelatedEntitiesRelation() {
        return new EntityComplexType.RelatedEntities.Relation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityComplexType }{@code >}}
     *
     */
    @XmlElementDecl(name = "Entity")
    public JAXBElement<EntityComplexType> createEntity(EntityComplexType value) {
        return new JAXBElement<EntityComplexType>(_Entity_QNAME, EntityComplexType.class, null, value);
    }



    /**
     * Create an instance of {@link Attribute }
     *
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Row }
     *
     */
    public Row createRow() {
        return new Row();
    }


    /**
     * Create an instance of {@link Rows }
     *
     */
    public Rows createRows() {
        return new Rows();
    }

    /**
     * Create an instance of {@link GraphResult }
     *
     */
    public GraphResult createGraphResult() {
        return new GraphResult();
    }


    /**
     * Create an instance of {@link Error }
     *
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Errors }
     *
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link MetadataAttributes }
     *
     */
    public MetadataAttributes createMetadataAttributes() {
        return new MetadataAttributes();
    }

    /**
     * Create an instance of {@link Column }
     *
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Values }
     *
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link Columns }
     *
     */
    public Columns createColumns() {
        return new Columns();
    }

    /**
     * Create an instance of {@link DataTable }
     *
     */
    public DataTable createDataTable() {
        return new DataTable();
    }
}
