//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.06.12 at 10:29:05 PM CST
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hp.com/ppm/integration/sass/agm/model")
package com.ppm.integration.agilesdk.connector.agm.model.jaxb;
